# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text=b'Categories for which to collect items.', related_name='listing_categories', to='category.Category'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='content',
            field=models.ManyToManyField(blank=True, help_text=b'Individual items to display. Setting this will ignore any setting for <i>Content Type</i>, <i>Categories</i> and <i>Tags</i>.', related_name='listing_content', through='listing.ListingContent', to='jmbo.ModelBase'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='content_types',
            field=models.ManyToManyField(blank=True, help_text=b'Content types to display, eg. post or gallery.', to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='pinned',
            field=models.ManyToManyField(blank=True, help_text=b'Individual items to pin to the top of the listing. These\nitems are visible across all pages when navigating the listing.', related_name='listing_pinned', through='listing.ListingPinned', to='jmbo.ModelBase'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='sites',
            field=models.ManyToManyField(blank=True, help_text=b'Sites that this listing will appear on.', to='sites.Site'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='style',
            field=models.CharField(choices=[(b'Horizontal', b'Horizontal'), (b'Vertical', b'Vertical'), (b'Promo', b'Promo'), (b'VerticalThumbnail', b'VerticalThumbnail'), (b'Widget', b'Widget'), (b'CustomOne', b'CustomOne'), (b'CustomTwo', b'CustomTwo'), (b'CustomThree', b'CustomThree'), (b'CustomFour', b'CustomFour'), (b'CustomFive', b'CustomFive')], max_length=64),
        ),
        migrations.AlterField(
            model_name='listing',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text=b'Tags for which to collect items.', related_name='listing_tags', to='category.Tag'),
        ),
    ]
