# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-25 07:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemodel',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='basemodel_categories', to='category.Category'),
        ),
        migrations.AlterField(
            model_name='basemodel',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='basemodel_tags', to='category.Tag'),
        ),
    ]
